export const LANG_MAP: Record<string, string> = {
  ".ts": "ts",
  ".tsx": "tsx",
  ".mts": "mts",
  ".cts": "cts",
  ".js": "js",
  ".jsx": "jsx",
  ".mjs": "mjs",
  ".cjs": "cjs",
  ".css": "css",
  ".md": "md",
  ".mdx": "mdx",
  ".mdc": "mdc",
  ".yml": "yaml",
  ".yaml": "yaml",
  ".txt": "txt",
  ".json": "json",
  ".sh": "sh",
};
